services:
  spark:
    image: bitnami/spark:3.4.1
    container_name: spark
    ports:
      - "4040:4040"  # Spark UI
    environment:
      SPARK_MODE: "master"
      SPARK_MASTER_URL: "spark://spark:7077"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - elasticsearch
    volumes:
      - /home/pubudu/capstone-project/apache-spark-job.py:/opt/spark-apps/apache-spark-job.py
      - /home/pubudu/capstone-project/apache-elastic-search-job.py:/opt/spark-apps/apache-elastic-search-job.py
      - /home/pubudu/capstone-project/spark-checkpoints:/opt/spark-apps/spark-checkpoints
  resource-monitor:
    build:
      context: .
      dockerfile: Dockerfile-RM
    container_name: resource-monitor
    environment:
      MQTT_BROKER: "vernemq"
      MQTT_TOPIC: "Resource/NodeMCU/Monitoring/#"
      MQTT_USERNAME: "admin"
      MQTT_PASSWORD: "admin"
      KAFKA_BROKER: "kafka1:9092"
      KAFKA_TOPIC: "logs"
    depends_on:
      - vernemq
      - kafka1
      - kafka2
      - kafka3
