# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the necessary dependencies
RUN pip install --no-cache-dir paho-mqtt kafka-python psutil

# Copy the Python script into the container
COPY mqtt-kafka-subscriber.py /app/

# Make port 1883 available to the world outside this container
EXPOSE 1883

# Run the Python script when the container launches
CMD ["python", "/app/mqtt-kafka-subscriber.py"]

